#!/usr/bin/env node
/**
 * Generates css/tokens.css and swift/SCTheme.swift from tokens/tokens.json.
 *
 * One JSON file feeds every platform, so a colour tweak lands identically in
 * the browser apps and the native apps instead of drifting between hand-kept
 * copies. Generated files carry a header saying so; edit the JSON, not them.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(fs.readFileSync(path.join(ROOT, 'tokens/tokens.json'), 'utf8'));

const HEADER = 'GENERATED by scripts/build-tokens.mjs from tokens/tokens.json. Do not edit by hand.';

/** [id, { name, mark, color }] for every app. A bare colour string still works for older token files. */
const apps = Object.entries(tokens.apps)
  .filter(([k]) => !k.startsWith('$'))
  .map(([id, v]) => [id, typeof v === 'string' ? { name: id, mark: id.slice(0, 2).toUpperCase(), color: v } : v]);

const rgb = (hex) => {
  const h = hex.replace('#', '');
  const n = parseInt(h.length === 3 ? h.replace(/./g, (c) => c + c) : h, 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
};

// ---------------------------------------------------------------- CSS ----

const css = [];
css.push(`/* ${HEADER} */`, '');

css.push(':root {');
for (const [role, f] of Object.entries(tokens.fonts)) {
  css.push(`  --sc-font-${role}: "${f.family}", ${f.fallback};`);
}
for (const [k, v] of Object.entries(tokens.size)) css.push(`  --sc-${k}: ${v};`);
for (const [k, v] of Object.entries(tokens.space)) css.push(`  --sc-space-${k}: ${v};`);
for (const [k, v] of Object.entries(tokens.shape)) css.push(`  --sc-${k}: ${v};`);
for (const [k, v] of Object.entries(tokens.motion)) css.push(`  --sc-${k === 'ease' ? 'ease' : `dur-${k}`}: ${v};`);
for (const [k, v] of Object.entries(tokens.status)) {
  css.push(`  --sc-${k}: ${v};`, `  --sc-${k}-rgb: ${rgb(v).join(' ')};`);
}
for (const [k, app] of apps) {
  css.push(`  --sc-app-${k}: ${app.color};`, `  --sc-app-${k}-rgb: ${rgb(app.color).join(' ')};`);
}
// The app accent defaults to the race accent until a page declares its app.
css.push('  --sc-app: var(--sc-accent);', '  --sc-app-rgb: var(--sc-accent-rgb);');
css.push('}', '');

const raceNames = Object.keys(tokens.races);
raceNames.forEach((race, i) => {
  const { colors } = tokens.races[race];
  // The first race is the default, so it also applies when no race is set.
  const selector = i === 0 ? `:root, [data-race="${race}"]` : `[data-race="${race}"]`;
  css.push(`${selector} {`);
  for (const [k, v] of Object.entries(colors)) {
    css.push(`  --sc-${k}: ${v};`, `  --sc-${k}-rgb: ${rgb(v).join(' ')};`);
  }
  // A race may bring its own status colours (the macOS appearances do).
  for (const [k, v] of Object.entries(tokens.races[race].status || {})) {
    css.push(`  --sc-${k}: ${v};`, `  --sc-${k}-rgb: ${rgb(v).join(' ')};`);
  }
  css.push('}', '');
});

for (const [app] of apps) {
  css.push(`[data-app="${app}"] {`, `  --sc-app: var(--sc-app-${app});`, `  --sc-app-rgb: var(--sc-app-${app}-rgb);`, '}', '');
}

fs.writeFileSync(path.join(ROOT, 'css/tokens.css'), css.join('\n'));

// -------------------------------------------------------------- Swift ----

const swiftName = (k) => k.replace(/-(\w)/g, (_, c) => c.toUpperCase());
const swiftColor = (hex) => {
  const [r, g, b] = rgb(hex);
  return `Color(red: ${(r / 255).toFixed(3)}, green: ${(g / 255).toFixed(3)}, blue: ${(b / 255).toFixed(3)})`;
};

const colorKeys = Object.keys(tokens.races[raceNames[0]].colors);
const swift = [];
swift.push(`// ${HEADER}`, '', 'import SwiftUI', '');
swift.push('/// Toolkit UI theme for SwiftUI apps. Mirrors css/tokens.css one-to-one: the HUD palettes');
swift.push('/// (steel, crystal, chitin) and the two macOS appearances (light, dark).');
swift.push('public enum SCRace: String, CaseIterable, Identifiable {');
for (const race of raceNames) swift.push(`    case ${race}`);
swift.push('    public var id: String { rawValue }');
swift.push('    public var label: String {', '        switch self {');
for (const race of raceNames) swift.push(`        case .${race}: return "${tokens.races[race].label}"`);
swift.push('        }', '    }');
swift.push('    public var palette: SCPalette {', '        switch self {');
for (const race of raceNames) swift.push(`        case .${race}: return .${race}`);
swift.push('        }', '    }', '}', '');

swift.push('public struct SCPalette {');
for (const k of colorKeys) swift.push(`    public let ${swiftName(k)}: Color`);
swift.push('');
for (const race of raceNames) {
  const { colors } = tokens.races[race];
  swift.push(`    public static let ${race} = SCPalette(`);
  swift.push(colorKeys.map((k) => `        ${swiftName(k)}: ${swiftColor(colors[k])}`).join(',\n'));
  swift.push('    )');
}
swift.push('}', '');

swift.push('public enum SCStatus {');
for (const [k, v] of Object.entries(tokens.status)) swift.push(`    public static let ${swiftName(k)} = ${swiftColor(v)}`);
swift.push('}', '');

swift.push('public enum SCAppColor {');
for (const [k, app] of apps) swift.push(`    public static let ${swiftName(k)} = ${swiftColor(app.color)}`);
swift.push('}', '');

swift.push('/// Each app as tokens.json lists it. The Launcher and any native app switcher read names,');
swift.push('/// marks and colours from here rather than keeping copies.');
swift.push('public struct SCAppInfo: Identifiable {');
swift.push('    public let id: String', '    public let name: String', '    public let mark: String', '    public let color: Color');
swift.push('}', '');
swift.push('public enum SCApps {', '    public static let all: [SCAppInfo] = [');
for (const [k, app] of apps) {
  swift.push(`        SCAppInfo(id: "${k}", name: "${app.name}", mark: "${app.mark}", color: SCAppColor.${swiftName(k)}),`);
}
swift.push('    ]', '    public static func app(_ id: String) -> SCAppInfo? { all.first { $0.id == id } }', '}', '');

swift.push('/// Font helpers. Bundle the TTF/OTF files of these families in the app target');
swift.push('/// (Google Fonts, OFL); the woff2 files in fonts/ are for the web only.');
swift.push('public enum SCFont {');
for (const [role, f] of Object.entries(tokens.fonts)) {
  swift.push(`    public static func ${role}(_ size: CGFloat, weight: Font.Weight = .regular) -> Font {`);
  swift.push(`        Font.custom("${f.family}", size: size).weight(weight)`);
  swift.push('    }');
}
swift.push('}', '');

fs.writeFileSync(path.join(ROOT, 'swift/SCTheme.swift'), swift.join('\n'));

console.log(`tokens: ${raceNames.length} races -> css/tokens.css, swift/SCTheme.swift`);
